### PR TITLE
Allows for OpenGL calls in the background.

### PR DESCRIPTION
**Pull request by hamzasood**
Changes to allow the Facebook app to successfully make OpenGL calls while it isn't the active app.

### CODE REVIEW

**Comment by b3ll** [comment]
Woah. How'd you figure out the process assertions? I tried 1<<3 but it wasn't enough… Were you checking out BKProcessAssertions?

**Comment by hamzasood** [comment]
I looked at where backboardd receives the XPC message to add a BKSProcessAssertion. It makes a BKProcessAssertion out of it and attaches it to the process. The flags are directly copied over (so the flags property of BKSProcessAssertion and BKProcessAssertion are the same). The disassembly of -[BKProcessAssertion setFlags:] showed the bit field extracts that were done and what it does if certain bits are set. So from that I could recreate the enum.

**Comment by b3ll** [comment]
Ah. I wasn't assuming BKS and BK were the same, I was looking at the XPC flags. Thanks for that!

**Comment by hamzasood** [comment]
I screwed up slightly though. "ProcessAssertionFlagPreventThrottleDownUI" should actually be "ProcessAssertionFlagWantsForegroundResourcePriority". Don't know how I missed that >_<

**Comment by b3ll** [comment]
Even still, having the GL calls and stuff makes it WAY more stable. I'll change that if you'd like

**Pull request merged**
